<?php

/**
 * BaseReklama_pozice
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property clob $popis
 * @property Doctrine_Collection $Reklama
 * 
 * @method integer             getId()      Returns the current record's "id" value
 * @method string              getName()    Returns the current record's "name" value
 * @method clob                getPopis()   Returns the current record's "popis" value
 * @method Doctrine_Collection getReklama() Returns the current record's "Reklama" collection
 * @method Reklama_pozice      setId()      Sets the current record's "id" value
 * @method Reklama_pozice      setName()    Sets the current record's "name" value
 * @method Reklama_pozice      setPopis()   Sets the current record's "popis" value
 * @method Reklama_pozice      setReklama() Sets the current record's "Reklama" collection
 * 
 * @package    caitalia
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseReklama_pozice extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('reklama_pozice');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('popis', 'clob', null, array(
             'type' => 'clob',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Reklama', array(
             'local' => 'id',
             'foreign' => 'reklama_pozice_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}