<?php

/**
 * BaseReklama
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $reklama_pozice_id
 * @property string $name
 * @property date $zacatek
 * @property date $konec
 * @property string $img
 * @property string $url
 * @property integer $imprese
 * @property clob $poznamka
 * @property integer $zobrazeno
 * @property ReklamaPozice $ReklamaPozice
 * @property Doctrine_Collection $Reklama_statistika
 * 
 * @method integer             getId()                 Returns the current record's "id" value
 * @method integer             getReklamaPoziceId()    Returns the current record's "reklama_pozice_id" value
 * @method string              getName()               Returns the current record's "name" value
 * @method date                getZacatek()            Returns the current record's "zacatek" value
 * @method date                getKonec()              Returns the current record's "konec" value
 * @method string              getImg()                Returns the current record's "img" value
 * @method string              getUrl()                Returns the current record's "url" value
 * @method integer             getImprese()            Returns the current record's "imprese" value
 * @method clob                getPoznamka()           Returns the current record's "poznamka" value
 * @method integer             getZobrazeno()          Returns the current record's "zobrazeno" value
 * @method ReklamaPozice       getReklamaPozice()      Returns the current record's "ReklamaPozice" value
 * @method Doctrine_Collection getReklamaStatistika()  Returns the current record's "Reklama_statistika" collection
 * @method Reklama             setId()                 Sets the current record's "id" value
 * @method Reklama             setReklamaPoziceId()    Sets the current record's "reklama_pozice_id" value
 * @method Reklama             setName()               Sets the current record's "name" value
 * @method Reklama             setZacatek()            Sets the current record's "zacatek" value
 * @method Reklama             setKonec()              Sets the current record's "konec" value
 * @method Reklama             setImg()                Sets the current record's "img" value
 * @method Reklama             setUrl()                Sets the current record's "url" value
 * @method Reklama             setImprese()            Sets the current record's "imprese" value
 * @method Reklama             setPoznamka()           Sets the current record's "poznamka" value
 * @method Reklama             setZobrazeno()          Sets the current record's "zobrazeno" value
 * @method Reklama             setReklamaPozice()      Sets the current record's "ReklamaPozice" value
 * @method Reklama             setReklamaStatistika()  Sets the current record's "Reklama_statistika" collection
 * 
 * @package    caitalia
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseReklama extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('reklama');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('reklama_pozice_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'unique' => true,
             'length' => 50,
             ));
        $this->hasColumn('zacatek', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('konec', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('img', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('imprese', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('poznamka', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('zobrazeno', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));


        $this->index('datum', array(
             'fields' => 
             array(
              'zacatek' => 
              array(
              'sorting' => 'ASC',
              ),
              'konec' => 
              array(
              'sorting' => 'ASC',
              ),
             ),
             ));
        $this->index('zobrazeni', array(
             'fields' => 
             array(
              'zobrazeno' => 
              array(
              'sorting' => 'DESC',
              ),
              'zacatek' => 
              array(
              'sorting' => 'ASC',
              ),
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ReklamaPozice', array(
             'local' => 'reklama_pozice_id',
             'foreign' => 'id'));

        $this->hasMany('Reklama_statistika', array(
             'local' => 'id',
             'foreign' => 'reklama_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}