<?php

/**
 * BaseReklama_statistika
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $reklama_id
 * @property integer $reklama_pozice_id
 * @property string $from_ip
 * @property string $user_agent
 * @property string $referer
 * @property string $url
 * @property Reklama $Reklama
 * @property ReklamaPozice $ReklamaPozice
 * 
 * @method integer            getId()                Returns the current record's "id" value
 * @method integer            getReklamaId()         Returns the current record's "reklama_id" value
 * @method integer            getReklamaPoziceId()   Returns the current record's "reklama_pozice_id" value
 * @method string             getFromIp()            Returns the current record's "from_ip" value
 * @method string             getUserAgent()         Returns the current record's "user_agent" value
 * @method string             getReferer()           Returns the current record's "referer" value
 * @method string             getUrl()               Returns the current record's "url" value
 * @method Reklama            getReklama()           Returns the current record's "Reklama" value
 * @method ReklamaPozice      getReklamaPozice()     Returns the current record's "ReklamaPozice" value
 * @method Reklama_statistika setId()                Sets the current record's "id" value
 * @method Reklama_statistika setReklamaId()         Sets the current record's "reklama_id" value
 * @method Reklama_statistika setReklamaPoziceId()   Sets the current record's "reklama_pozice_id" value
 * @method Reklama_statistika setFromIp()            Sets the current record's "from_ip" value
 * @method Reklama_statistika setUserAgent()         Sets the current record's "user_agent" value
 * @method Reklama_statistika setReferer()           Sets the current record's "referer" value
 * @method Reklama_statistika setUrl()               Sets the current record's "url" value
 * @method Reklama_statistika setReklama()           Sets the current record's "Reklama" value
 * @method Reklama_statistika setReklamaPozice()     Sets the current record's "ReklamaPozice" value
 * 
 * @package    caitalia
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseReklama_statistika extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('reklama_statistika');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('reklama_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('reklama_pozice_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('from_ip', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('user_agent', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('referer', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Reklama', array(
             'local' => 'reklama_id',
             'foreign' => 'id'));

        $this->hasOne('ReklamaPozice', array(
             'local' => 'reklama_pozice_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}