<?php

/**
 * BaseCenyRadky
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property bigint $ceny_id
 * @property boolean $is_active
 * @property integer $radek
 * @property date $sl_od
 * @property date $sl_do
 * @property integer $min_noc
 * @property float $sl1
 * @property float $sl2
 * @property float $sl3
 * @property float $sl4
 * @property float $sl5
 * @property float $sl6
 * @property float $sl7
 * @property float $sl8
 * @property float $sl9
 * @property float $bonus1
 * @property string $bonus1_p
 * @property float $bonus2
 * @property string $bonus2_p
 * @property float $bonus3
 * @property string $bonus3_p
 * @property float $bonus4
 * @property string $bonus4_p
 * @property float $bonus5
 * @property string $bonus5_p
 * @property float $bonus6
 * @property string $bonus6_p
 * @property float $bonus7
 * @property string $bonus7_p
 * @property float $bonus8
 * @property string $bonus8_p
 * @property float $bonus9
 * @property string $bonus9_p
 * @property float $sleva1
 * @property string $sleva1_p
 * @property float $sleva2
 * @property string $sleva2_p
 * @property float $sleva3
 * @property string $sleva3_p
 * @property float $sleva4
 * @property string $sleva4_p
 * @property float $sleva5
 * @property string $sleva5_p
 * @property float $sleva6
 * @property string $sleva6_p
 * @property float $sleva7
 * @property string $sleva7_p
 * @property float $sleva8
 * @property string $sleva8_p
 * @property float $sleva9
 * @property string $sleva9_p
 * @property Ceny $Ceny
 * 
 * @method bigint    getCenyId()    Returns the current record's "ceny_id" value
 * @method boolean   getIsActive()  Returns the current record's "is_active" value
 * @method integer   getRadek()     Returns the current record's "radek" value
 * @method date      getSlOd()      Returns the current record's "sl_od" value
 * @method date      getSlDo()      Returns the current record's "sl_do" value
 * @method integer   getMinNoc()    Returns the current record's "min_noc" value
 * @method float     getSl1()       Returns the current record's "sl1" value
 * @method float     getSl2()       Returns the current record's "sl2" value
 * @method float     getSl3()       Returns the current record's "sl3" value
 * @method float     getSl4()       Returns the current record's "sl4" value
 * @method float     getSl5()       Returns the current record's "sl5" value
 * @method float     getSl6()       Returns the current record's "sl6" value
 * @method float     getSl7()       Returns the current record's "sl7" value
 * @method float     getSl8()       Returns the current record's "sl8" value
 * @method float     getSl9()       Returns the current record's "sl9" value
 * @method float     getBonus1()    Returns the current record's "bonus1" value
 * @method string    getBonus1P()   Returns the current record's "bonus1_p" value
 * @method float     getBonus2()    Returns the current record's "bonus2" value
 * @method string    getBonus2P()   Returns the current record's "bonus2_p" value
 * @method float     getBonus3()    Returns the current record's "bonus3" value
 * @method string    getBonus3P()   Returns the current record's "bonus3_p" value
 * @method float     getBonus4()    Returns the current record's "bonus4" value
 * @method string    getBonus4P()   Returns the current record's "bonus4_p" value
 * @method float     getBonus5()    Returns the current record's "bonus5" value
 * @method string    getBonus5P()   Returns the current record's "bonus5_p" value
 * @method float     getBonus6()    Returns the current record's "bonus6" value
 * @method string    getBonus6P()   Returns the current record's "bonus6_p" value
 * @method float     getBonus7()    Returns the current record's "bonus7" value
 * @method string    getBonus7P()   Returns the current record's "bonus7_p" value
 * @method float     getBonus8()    Returns the current record's "bonus8" value
 * @method string    getBonus8P()   Returns the current record's "bonus8_p" value
 * @method float     getBonus9()    Returns the current record's "bonus9" value
 * @method string    getBonus9P()   Returns the current record's "bonus9_p" value
 * @method float     getSleva1()    Returns the current record's "sleva1" value
 * @method string    getSleva1P()   Returns the current record's "sleva1_p" value
 * @method float     getSleva2()    Returns the current record's "sleva2" value
 * @method string    getSleva2P()   Returns the current record's "sleva2_p" value
 * @method float     getSleva3()    Returns the current record's "sleva3" value
 * @method string    getSleva3P()   Returns the current record's "sleva3_p" value
 * @method float     getSleva4()    Returns the current record's "sleva4" value
 * @method string    getSleva4P()   Returns the current record's "sleva4_p" value
 * @method float     getSleva5()    Returns the current record's "sleva5" value
 * @method string    getSleva5P()   Returns the current record's "sleva5_p" value
 * @method float     getSleva6()    Returns the current record's "sleva6" value
 * @method string    getSleva6P()   Returns the current record's "sleva6_p" value
 * @method float     getSleva7()    Returns the current record's "sleva7" value
 * @method string    getSleva7P()   Returns the current record's "sleva7_p" value
 * @method float     getSleva8()    Returns the current record's "sleva8" value
 * @method string    getSleva8P()   Returns the current record's "sleva8_p" value
 * @method float     getSleva9()    Returns the current record's "sleva9" value
 * @method string    getSleva9P()   Returns the current record's "sleva9_p" value
 * @method Ceny      getCeny()      Returns the current record's "Ceny" value
 * @method CenyRadky setCenyId()    Sets the current record's "ceny_id" value
 * @method CenyRadky setIsActive()  Sets the current record's "is_active" value
 * @method CenyRadky setRadek()     Sets the current record's "radek" value
 * @method CenyRadky setSlOd()      Sets the current record's "sl_od" value
 * @method CenyRadky setSlDo()      Sets the current record's "sl_do" value
 * @method CenyRadky setMinNoc()    Sets the current record's "min_noc" value
 * @method CenyRadky setSl1()       Sets the current record's "sl1" value
 * @method CenyRadky setSl2()       Sets the current record's "sl2" value
 * @method CenyRadky setSl3()       Sets the current record's "sl3" value
 * @method CenyRadky setSl4()       Sets the current record's "sl4" value
 * @method CenyRadky setSl5()       Sets the current record's "sl5" value
 * @method CenyRadky setSl6()       Sets the current record's "sl6" value
 * @method CenyRadky setSl7()       Sets the current record's "sl7" value
 * @method CenyRadky setSl8()       Sets the current record's "sl8" value
 * @method CenyRadky setSl9()       Sets the current record's "sl9" value
 * @method CenyRadky setBonus1()    Sets the current record's "bonus1" value
 * @method CenyRadky setBonus1P()   Sets the current record's "bonus1_p" value
 * @method CenyRadky setBonus2()    Sets the current record's "bonus2" value
 * @method CenyRadky setBonus2P()   Sets the current record's "bonus2_p" value
 * @method CenyRadky setBonus3()    Sets the current record's "bonus3" value
 * @method CenyRadky setBonus3P()   Sets the current record's "bonus3_p" value
 * @method CenyRadky setBonus4()    Sets the current record's "bonus4" value
 * @method CenyRadky setBonus4P()   Sets the current record's "bonus4_p" value
 * @method CenyRadky setBonus5()    Sets the current record's "bonus5" value
 * @method CenyRadky setBonus5P()   Sets the current record's "bonus5_p" value
 * @method CenyRadky setBonus6()    Sets the current record's "bonus6" value
 * @method CenyRadky setBonus6P()   Sets the current record's "bonus6_p" value
 * @method CenyRadky setBonus7()    Sets the current record's "bonus7" value
 * @method CenyRadky setBonus7P()   Sets the current record's "bonus7_p" value
 * @method CenyRadky setBonus8()    Sets the current record's "bonus8" value
 * @method CenyRadky setBonus8P()   Sets the current record's "bonus8_p" value
 * @method CenyRadky setBonus9()    Sets the current record's "bonus9" value
 * @method CenyRadky setBonus9P()   Sets the current record's "bonus9_p" value
 * @method CenyRadky setSleva1()    Sets the current record's "sleva1" value
 * @method CenyRadky setSleva1P()   Sets the current record's "sleva1_p" value
 * @method CenyRadky setSleva2()    Sets the current record's "sleva2" value
 * @method CenyRadky setSleva2P()   Sets the current record's "sleva2_p" value
 * @method CenyRadky setSleva3()    Sets the current record's "sleva3" value
 * @method CenyRadky setSleva3P()   Sets the current record's "sleva3_p" value
 * @method CenyRadky setSleva4()    Sets the current record's "sleva4" value
 * @method CenyRadky setSleva4P()   Sets the current record's "sleva4_p" value
 * @method CenyRadky setSleva5()    Sets the current record's "sleva5" value
 * @method CenyRadky setSleva5P()   Sets the current record's "sleva5_p" value
 * @method CenyRadky setSleva6()    Sets the current record's "sleva6" value
 * @method CenyRadky setSleva6P()   Sets the current record's "sleva6_p" value
 * @method CenyRadky setSleva7()    Sets the current record's "sleva7" value
 * @method CenyRadky setSleva7P()   Sets the current record's "sleva7_p" value
 * @method CenyRadky setSleva8()    Sets the current record's "sleva8" value
 * @method CenyRadky setSleva8P()   Sets the current record's "sleva8_p" value
 * @method CenyRadky setSleva9()    Sets the current record's "sleva9" value
 * @method CenyRadky setSleva9P()   Sets the current record's "sleva9_p" value
 * @method CenyRadky setCeny()      Sets the current record's "Ceny" value
 * 
 * @package    caitalia
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCenyRadky extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ceny_radky');
        $this->hasColumn('ceny_id', 'bigint', 20, array(
             'type' => 'bigint',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => true,
             ));
        $this->hasColumn('radek', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('sl_od', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('sl_do', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('min_noc', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('sl1', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('sl2', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('sl3', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('sl4', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('sl5', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('sl6', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('sl7', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('sl8', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('sl9', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('bonus1', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('bonus1_p', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('bonus2', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('bonus2_p', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('bonus3', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('bonus3_p', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('bonus4', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('bonus4_p', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('bonus5', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('bonus5_p', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('bonus6', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('bonus6_p', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('bonus7', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('bonus7_p', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('bonus8', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('bonus8_p', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('bonus9', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('bonus9_p', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('sleva1', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('sleva1_p', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('sleva2', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('sleva2_p', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('sleva3', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('sleva3_p', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('sleva4', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('sleva4_p', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('sleva5', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('sleva5_p', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('sleva6', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('sleva6_p', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('sleva7', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('sleva7_p', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('sleva8', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('sleva8_p', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('sleva9', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('sleva9_p', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));


        $this->index('sort', array(
             'fields' => 
             array(
              'ceny_id' => 
              array(
              'sorting' => 'ASC',
              ),
              'is_active' => 
              array(
              'sorting' => 'ASC',
              ),
              'radek' => 
              array(
              'sorting' => 'ASC',
              ),
              'sl_od' => 
              array(
              'sorting' => 'ASC',
              ),
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Ceny', array(
             'local' => 'ceny_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}