<?php

/**
 * BaseOblast
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property clob $popis
 * @property integer $destinace_id
 * @property enum $kat
 * @property string $adr_map_google
 * @property Destinace $Destinace
 * @property Doctrine_Collection $Zajezdy
 * 
 * @method integer             getId()             Returns the current record's "id" value
 * @method string              getName()           Returns the current record's "name" value
 * @method clob                getPopis()          Returns the current record's "popis" value
 * @method integer             getDestinaceId()    Returns the current record's "destinace_id" value
 * @method enum                getKat()            Returns the current record's "kat" value
 * @method string              getAdrMapGoogle()   Returns the current record's "adr_map_google" value
 * @method Destinace           getDestinace()      Returns the current record's "Destinace" value
 * @method Doctrine_Collection getZajezdy()        Returns the current record's "Zajezdy" collection
 * @method Oblast              setId()             Sets the current record's "id" value
 * @method Oblast              setName()           Sets the current record's "name" value
 * @method Oblast              setPopis()          Sets the current record's "popis" value
 * @method Oblast              setDestinaceId()    Sets the current record's "destinace_id" value
 * @method Oblast              setKat()            Sets the current record's "kat" value
 * @method Oblast              setAdrMapGoogle()   Sets the current record's "adr_map_google" value
 * @method Oblast              setDestinace()      Sets the current record's "Destinace" value
 * @method Oblast              setZajezdy()        Sets the current record's "Zajezdy" collection
 * 
 * @package    caitalia
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOblast extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('oblast');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('popis', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('destinace_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('kat', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Leto',
              1 => 'Zima',
              2 => 'Agroturistika',
             ),
             'default' => 'Leto',
             ));
        $this->hasColumn('adr_map_google', 'string', 25, array(
             'type' => 'string',
             'length' => '25',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Destinace', array(
             'local' => 'destinace_id',
             'foreign' => 'id'));

        $this->hasMany('Zajezdy', array(
             'local' => 'id',
             'foreign' => 'oblast_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'Sluggable' => NULL,
             'unique' => true,
             'fields' => 
             array(
              0 => 'name',
             ),
             'canUpdate' => true,
             ));
        $this->actAs($timestampable0);
    }
}