<?php

/**
 * BaseSettingItalia2012
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $SiteName
 * @property string $email
 * @property string $tel
 * @property string $mobil
 * @property clob $pracovni_doba
 * @property string $ulice
 * @property string $mesto
 * @property integer $pocet_na_hp
 * @property string $adr_map_google
 * @property string $web_adr
 * @property string $ga_code
 * @property string $google_overeni
 * 
 * @method integer           getId()             Returns the current record's "id" value
 * @method string            getSiteName()       Returns the current record's "SiteName" value
 * @method string            getEmail()          Returns the current record's "email" value
 * @method string            getTel()            Returns the current record's "tel" value
 * @method string            getMobil()          Returns the current record's "mobil" value
 * @method clob              getPracovniDoba()   Returns the current record's "pracovni_doba" value
 * @method string            getUlice()          Returns the current record's "ulice" value
 * @method string            getMesto()          Returns the current record's "mesto" value
 * @method integer           getPocetNaHp()      Returns the current record's "pocet_na_hp" value
 * @method string            getAdrMapGoogle()   Returns the current record's "adr_map_google" value
 * @method string            getWebAdr()         Returns the current record's "web_adr" value
 * @method string            getGaCode()         Returns the current record's "ga_code" value
 * @method string            getGoogleOvereni()  Returns the current record's "google_overeni" value
 * @method SettingItalia2012 setId()             Sets the current record's "id" value
 * @method SettingItalia2012 setSiteName()       Sets the current record's "SiteName" value
 * @method SettingItalia2012 setEmail()          Sets the current record's "email" value
 * @method SettingItalia2012 setTel()            Sets the current record's "tel" value
 * @method SettingItalia2012 setMobil()          Sets the current record's "mobil" value
 * @method SettingItalia2012 setPracovniDoba()   Sets the current record's "pracovni_doba" value
 * @method SettingItalia2012 setUlice()          Sets the current record's "ulice" value
 * @method SettingItalia2012 setMesto()          Sets the current record's "mesto" value
 * @method SettingItalia2012 setPocetNaHp()      Sets the current record's "pocet_na_hp" value
 * @method SettingItalia2012 setAdrMapGoogle()   Sets the current record's "adr_map_google" value
 * @method SettingItalia2012 setWebAdr()         Sets the current record's "web_adr" value
 * @method SettingItalia2012 setGaCode()         Sets the current record's "ga_code" value
 * @method SettingItalia2012 setGoogleOvereni()  Sets the current record's "google_overeni" value
 * 
 * @package    caitalia
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSettingItalia2012 extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('setting_italia2012');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('SiteName', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('email', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('tel', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('mobil', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('pracovni_doba', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('ulice', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('mesto', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('pocet_na_hp', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('adr_map_google', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('web_adr', 'string', 55, array(
             'type' => 'string',
             'length' => 55,
             ));
        $this->hasColumn('ga_code', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('google_overeni', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}