<?php

/**
 * BaseDestinaceRegiony
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $destinace_id
 * @property integer $regiony_id
 * 
 * @method integer          getDestinaceId()  Returns the current record's "destinace_id" value
 * @method integer          getRegionyId()    Returns the current record's "regiony_id" value
 * @method DestinaceRegiony setDestinaceId()  Sets the current record's "destinace_id" value
 * @method DestinaceRegiony setRegionyId()    Sets the current record's "regiony_id" value
 * 
 * @package    caitalia
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDestinaceRegiony extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('destinace_regiony');
        $this->hasColumn('destinace_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('regiony_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}