<?php

/**
 * BaseDestinace
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $img
 * @property enum $kat
 * @property clob $popis
 * @property string $keywords
 * @property string $description
 * @property integer $poradi
 * @property string $adr_map_google
 * @property integer $regiony_id
 * @property boolean $publikovat_italie
 * @property integer $poradi_italie
 * @property float $cena_od_italie
 * @property string $cena_od_italie_ozna
 * @property clob $popisek_italie
 * @property integer $pozice_italie_x
 * @property integer $pozice_italie_y
 * @property Doctrine_Collection $Kategorie
 * @property Regiony $Regiony
 * @property Doctrine_Collection $Oblast
 * @property Doctrine_Collection $Zajezdy
 * 
 * @method integer             getId()                  Returns the current record's "id" value
 * @method string              getName()                Returns the current record's "name" value
 * @method string              getImg()                 Returns the current record's "img" value
 * @method enum                getKat()                 Returns the current record's "kat" value
 * @method clob                getPopis()               Returns the current record's "popis" value
 * @method string              getKeywords()            Returns the current record's "keywords" value
 * @method string              getDescription()         Returns the current record's "description" value
 * @method integer             getPoradi()              Returns the current record's "poradi" value
 * @method string              getAdrMapGoogle()        Returns the current record's "adr_map_google" value
 * @method integer             getRegionyId()           Returns the current record's "regiony_id" value
 * @method boolean             getPublikovatItalie()    Returns the current record's "publikovat_italie" value
 * @method integer             getPoradiItalie()        Returns the current record's "poradi_italie" value
 * @method float               getCenaOdItalie()        Returns the current record's "cena_od_italie" value
 * @method string              getCenaOdItalieOzna()    Returns the current record's "cena_od_italie_ozna" value
 * @method clob                getPopisekItalie()       Returns the current record's "popisek_italie" value
 * @method integer             getPoziceItalieX()       Returns the current record's "pozice_italie_x" value
 * @method integer             getPoziceItalieY()       Returns the current record's "pozice_italie_y" value
 * @method Doctrine_Collection getKategorie()           Returns the current record's "Kategorie" collection
 * @method Regiony             getRegiony()             Returns the current record's "Regiony" value
 * @method Doctrine_Collection getOblast()              Returns the current record's "Oblast" collection
 * @method Doctrine_Collection getZajezdy()             Returns the current record's "Zajezdy" collection
 * @method Destinace           setId()                  Sets the current record's "id" value
 * @method Destinace           setName()                Sets the current record's "name" value
 * @method Destinace           setImg()                 Sets the current record's "img" value
 * @method Destinace           setKat()                 Sets the current record's "kat" value
 * @method Destinace           setPopis()               Sets the current record's "popis" value
 * @method Destinace           setKeywords()            Sets the current record's "keywords" value
 * @method Destinace           setDescription()         Sets the current record's "description" value
 * @method Destinace           setPoradi()              Sets the current record's "poradi" value
 * @method Destinace           setAdrMapGoogle()        Sets the current record's "adr_map_google" value
 * @method Destinace           setRegionyId()           Sets the current record's "regiony_id" value
 * @method Destinace           setPublikovatItalie()    Sets the current record's "publikovat_italie" value
 * @method Destinace           setPoradiItalie()        Sets the current record's "poradi_italie" value
 * @method Destinace           setCenaOdItalie()        Sets the current record's "cena_od_italie" value
 * @method Destinace           setCenaOdItalieOzna()    Sets the current record's "cena_od_italie_ozna" value
 * @method Destinace           setPopisekItalie()       Sets the current record's "popisek_italie" value
 * @method Destinace           setPoziceItalieX()       Sets the current record's "pozice_italie_x" value
 * @method Destinace           setPoziceItalieY()       Sets the current record's "pozice_italie_y" value
 * @method Destinace           setKategorie()           Sets the current record's "Kategorie" collection
 * @method Destinace           setRegiony()             Sets the current record's "Regiony" value
 * @method Destinace           setOblast()              Sets the current record's "Oblast" collection
 * @method Destinace           setZajezdy()             Sets the current record's "Zajezdy" collection
 * 
 * @package    caitalia
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDestinace extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('destinace');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('img', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('kat', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Leto',
              1 => 'Zima',
              2 => 'Agroturistika',
             ),
             'default' => 'Leto',
             ));
        $this->hasColumn('popis', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('keywords', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('poradi', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('adr_map_google', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('regiony_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('publikovat_italie', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('poradi_italie', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('cena_od_italie', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('cena_od_italie_ozna', 'string', 25, array(
             'type' => 'string',
             'length' => 25,
             ));
        $this->hasColumn('popisek_italie', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('pozice_italie_x', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('pozice_italie_y', 'integer', null, array(
             'type' => 'integer',
             ));


        $this->index('sorting', array(
             'fields' => 
             array(
              'poradi' => 
              array(
              'sorting' => 'ASC',
              ),
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Kategorie', array(
             'refClass' => 'DestinaceKategorie',
             'local' => 'kategorie_id',
             'foreign' => 'destinace_id'));

        $this->hasOne('Regiony', array(
             'local' => 'regiony_id',
             'foreign' => 'id'));

        $this->hasMany('Oblast', array(
             'local' => 'id',
             'foreign' => 'destinace_id'));

        $this->hasMany('Zajezdy', array(
             'local' => 'id',
             'foreign' => 'destinace_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'name',
             ),
             'canUpdate' => true,
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}