<?php

/**
 * BaseCenaTyp
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $zkratka
 * @property string $nazev
 * @property clob $popis
 * @property Doctrine_Collection $Zajezdy
 * 
 * @method string              getName()    Returns the current record's "name" value
 * @method string              getZkratka() Returns the current record's "zkratka" value
 * @method string              getNazev()   Returns the current record's "nazev" value
 * @method clob                getPopis()   Returns the current record's "popis" value
 * @method Doctrine_Collection getZajezdy() Returns the current record's "Zajezdy" collection
 * @method CenaTyp             setName()    Sets the current record's "name" value
 * @method CenaTyp             setZkratka() Sets the current record's "zkratka" value
 * @method CenaTyp             setNazev()   Sets the current record's "nazev" value
 * @method CenaTyp             setPopis()   Sets the current record's "popis" value
 * @method CenaTyp             setZajezdy() Sets the current record's "Zajezdy" collection
 * 
 * @package    caitalia
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCenaTyp extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cena_typ');
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('zkratka', 'string', 10, array(
             'type' => 'string',
             'length' => 10,
             ));
        $this->hasColumn('nazev', 'string', 25, array(
             'type' => 'string',
             'length' => 25,
             ));
        $this->hasColumn('popis', 'clob', null, array(
             'type' => 'clob',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Zajezdy', array(
             'local' => 'id',
             'foreign' => 'cena_typ'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}