<?php

/**
 * BaseZajezdyKategorie
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $zajezdy_id
 * @property integer $kategorie_id
 * @property integer $id
 * 
 * @method integer          getZajezdyId()    Returns the current record's "zajezdy_id" value
 * @method integer          getKategorieId()  Returns the current record's "kategorie_id" value
 * @method integer          getId()           Returns the current record's "id" value
 * @method ZajezdyKategorie setZajezdyId()    Sets the current record's "zajezdy_id" value
 * @method ZajezdyKategorie setKategorieId()  Sets the current record's "kategorie_id" value
 * @method ZajezdyKategorie setId()           Sets the current record's "id" value
 * 
 * @package    caitalia
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseZajezdyKategorie extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('zajezdy_kategorie');
        $this->hasColumn('zajezdy_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('kategorie_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}