<?php

/**
 * BaseSetting
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $SiteName
 * @property string $email
 * @property string $tel
 * @property string $mobil
 * @property clob $pracovni_doba
 * @property string $ulice
 * @property string $mesto
 * @property integer $pocet_na_hp
 * @property string $adr_map_google
 * @property string $email_rezervace
 * @property string $email_rez_nazev
 * @property string $email_dotaz
 * @property string $email_dotaz_nazev
 * @property string $logo_alt
 * @property string $logo_title
 * @property string $web_adr
 * @property string $ga_code
 * @property string $google_overeni
 * @property boolean $HP_slideshow
 * @property integer $HP_slideshow_interval
 * 
 * @method integer getId()                    Returns the current record's "id" value
 * @method string  getSiteName()              Returns the current record's "SiteName" value
 * @method string  getEmail()                 Returns the current record's "email" value
 * @method string  getTel()                   Returns the current record's "tel" value
 * @method string  getMobil()                 Returns the current record's "mobil" value
 * @method clob    getPracovniDoba()          Returns the current record's "pracovni_doba" value
 * @method string  getUlice()                 Returns the current record's "ulice" value
 * @method string  getMesto()                 Returns the current record's "mesto" value
 * @method integer getPocetNaHp()             Returns the current record's "pocet_na_hp" value
 * @method string  getAdrMapGoogle()          Returns the current record's "adr_map_google" value
 * @method string  getEmailRezervace()        Returns the current record's "email_rezervace" value
 * @method string  getEmailRezNazev()         Returns the current record's "email_rez_nazev" value
 * @method string  getEmailDotaz()            Returns the current record's "email_dotaz" value
 * @method string  getEmailDotazNazev()       Returns the current record's "email_dotaz_nazev" value
 * @method string  getLogoAlt()               Returns the current record's "logo_alt" value
 * @method string  getLogoTitle()             Returns the current record's "logo_title" value
 * @method string  getWebAdr()                Returns the current record's "web_adr" value
 * @method string  getGaCode()                Returns the current record's "ga_code" value
 * @method string  getGoogleOvereni()         Returns the current record's "google_overeni" value
 * @method boolean getHPSlideshow()           Returns the current record's "HP_slideshow" value
 * @method integer getHPSlideshowInterval()   Returns the current record's "HP_slideshow_interval" value
 * @method Setting setId()                    Sets the current record's "id" value
 * @method Setting setSiteName()              Sets the current record's "SiteName" value
 * @method Setting setEmail()                 Sets the current record's "email" value
 * @method Setting setTel()                   Sets the current record's "tel" value
 * @method Setting setMobil()                 Sets the current record's "mobil" value
 * @method Setting setPracovniDoba()          Sets the current record's "pracovni_doba" value
 * @method Setting setUlice()                 Sets the current record's "ulice" value
 * @method Setting setMesto()                 Sets the current record's "mesto" value
 * @method Setting setPocetNaHp()             Sets the current record's "pocet_na_hp" value
 * @method Setting setAdrMapGoogle()          Sets the current record's "adr_map_google" value
 * @method Setting setEmailRezervace()        Sets the current record's "email_rezervace" value
 * @method Setting setEmailRezNazev()         Sets the current record's "email_rez_nazev" value
 * @method Setting setEmailDotaz()            Sets the current record's "email_dotaz" value
 * @method Setting setEmailDotazNazev()       Sets the current record's "email_dotaz_nazev" value
 * @method Setting setLogoAlt()               Sets the current record's "logo_alt" value
 * @method Setting setLogoTitle()             Sets the current record's "logo_title" value
 * @method Setting setWebAdr()                Sets the current record's "web_adr" value
 * @method Setting setGaCode()                Sets the current record's "ga_code" value
 * @method Setting setGoogleOvereni()         Sets the current record's "google_overeni" value
 * @method Setting setHPSlideshow()           Sets the current record's "HP_slideshow" value
 * @method Setting setHPSlideshowInterval()   Sets the current record's "HP_slideshow_interval" value
 * 
 * @package    caitalia
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSetting extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('setting');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('SiteName', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('email', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('tel', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('mobil', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('pracovni_doba', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('ulice', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('mesto', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('pocet_na_hp', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('adr_map_google', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('email_rezervace', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('email_rez_nazev', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('email_dotaz', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('email_dotaz_nazev', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('logo_alt', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('logo_title', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('web_adr', 'string', 55, array(
             'type' => 'string',
             'length' => 55,
             ));
        $this->hasColumn('ga_code', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('google_overeni', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('HP_slideshow', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('HP_slideshow_interval', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}