<?php

/**
 * BaseZajezdy
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property integer $destinace_id
 * @property integer $oblast_id
 * @property enum $kat
 * @property integer $typ_id
 * @property float $cena_od
 * @property integer $cena_typ
 * @property integer $ceny_id
 * @property integer $ceny2_id
 * @property string $obrazek
 * @property integer $gallery_id
 * @property boolean $publikovat
 * @property integer $max_pocet_osob
 * @property integer $max_pristilka
 * @property clob $popis_list
 * @property clob $popis_detail
 * @property boolean $last_minute
 * @property float $cena_last_minute
 * @property date $last_minute_do
 * @property integer $ceny_last_minute_id
 * @property integer $ceny_last_minute2_id
 * @property clob $popis_pod_cenikem
 * @property boolean $akce
 * @property boolean $autobus
 * @property boolean $parkoviste
 * @property boolean $klimatizace
 * @property boolean $bazen
 * @property boolean $strava
 * @property boolean $internet
 * @property boolean $plazovy_servis
 * @property boolean $tv
 * @property boolean $zvire
 * @property string $adr_map_google
 * @property date $promovat_hp_do
 * @property integer $promovat_hp_pos
 * @property string $keywords
 * @property string $description
 * @property integer $detail
 * @property integer $zobrazeno
 * @property integer $imprese
 * @property date $zacatek
 * @property date $konec
 * @property integer $poradi
 * @property Gallery $Gallery
 * @property Typ $Typ
 * @property Oblast $Oblast
 * @property Destinace $Destinace
 * @property Ceny $Ceny
 * @property Ceny $CenyLastMinute
 * @property Ceny $Ceny2
 * @property Ceny $CenyLastMinute2
 * @property CenaTyp $CenaTyp
 * @property Doctrine_Collection $Hp_promovat
 * @property Doctrine_Collection $Aktuality
 * 
 * @method integer             getId()                   Returns the current record's "id" value
 * @method string              getName()                 Returns the current record's "name" value
 * @method integer             getDestinaceId()          Returns the current record's "destinace_id" value
 * @method integer             getOblastId()             Returns the current record's "oblast_id" value
 * @method enum                getKat()                  Returns the current record's "kat" value
 * @method integer             getTypId()                Returns the current record's "typ_id" value
 * @method float               getCenaOd()               Returns the current record's "cena_od" value
 * @method integer             getCenaTyp()              Returns the current record's "cena_typ" value
 * @method integer             getCenyId()               Returns the current record's "ceny_id" value
 * @method integer             getCeny2Id()              Returns the current record's "ceny2_id" value
 * @method string              getObrazek()              Returns the current record's "obrazek" value
 * @method integer             getGalleryId()            Returns the current record's "gallery_id" value
 * @method boolean             getPublikovat()           Returns the current record's "publikovat" value
 * @method integer             getMaxPocetOsob()         Returns the current record's "max_pocet_osob" value
 * @method integer             getMaxPristilka()         Returns the current record's "max_pristilka" value
 * @method clob                getPopisList()            Returns the current record's "popis_list" value
 * @method clob                getPopisDetail()          Returns the current record's "popis_detail" value
 * @method boolean             getLastMinute()           Returns the current record's "last_minute" value
 * @method float               getCenaLastMinute()       Returns the current record's "cena_last_minute" value
 * @method date                getLastMinuteDo()         Returns the current record's "last_minute_do" value
 * @method integer             getCenyLastMinuteId()     Returns the current record's "ceny_last_minute_id" value
 * @method integer             getCenyLastMinute2Id()    Returns the current record's "ceny_last_minute2_id" value
 * @method clob                getPopisPodCenikem()      Returns the current record's "popis_pod_cenikem" value
 * @method boolean             getAkce()                 Returns the current record's "akce" value
 * @method boolean             getAutobus()              Returns the current record's "autobus" value
 * @method boolean             getParkoviste()           Returns the current record's "parkoviste" value
 * @method boolean             getKlimatizace()          Returns the current record's "klimatizace" value
 * @method boolean             getBazen()                Returns the current record's "bazen" value
 * @method boolean             getStrava()               Returns the current record's "strava" value
 * @method boolean             getInternet()             Returns the current record's "internet" value
 * @method boolean             getPlazovyServis()        Returns the current record's "plazovy_servis" value
 * @method boolean             getTv()                   Returns the current record's "tv" value
 * @method boolean             getZvire()                Returns the current record's "zvire" value
 * @method string              getAdrMapGoogle()         Returns the current record's "adr_map_google" value
 * @method date                getPromovatHpDo()         Returns the current record's "promovat_hp_do" value
 * @method integer             getPromovatHpPos()        Returns the current record's "promovat_hp_pos" value
 * @method string              getKeywords()             Returns the current record's "keywords" value
 * @method string              getDescription()          Returns the current record's "description" value
 * @method integer             getDetail()               Returns the current record's "detail" value
 * @method integer             getZobrazeno()            Returns the current record's "zobrazeno" value
 * @method integer             getImprese()              Returns the current record's "imprese" value
 * @method date                getZacatek()              Returns the current record's "zacatek" value
 * @method date                getKonec()                Returns the current record's "konec" value
 * @method integer             getPoradi()               Returns the current record's "poradi" value
 * @method Gallery             getGallery()              Returns the current record's "Gallery" value
 * @method Typ                 getTyp()                  Returns the current record's "Typ" value
 * @method Oblast              getOblast()               Returns the current record's "Oblast" value
 * @method Destinace           getDestinace()            Returns the current record's "Destinace" value
 * @method Ceny                getCeny()                 Returns the current record's "Ceny" value
 * @method Ceny                getCenyLastMinute()       Returns the current record's "CenyLastMinute" value
 * @method Ceny                getCeny2()                Returns the current record's "Ceny2" value
 * @method Ceny                getCenyLastMinute2()      Returns the current record's "CenyLastMinute2" value
 * @method CenaTyp             getCenaTyp()              Returns the current record's "CenaTyp" value
 * @method Doctrine_Collection getHpPromovat()           Returns the current record's "Hp_promovat" collection
 * @method Doctrine_Collection getAktuality()            Returns the current record's "Aktuality" collection
 * @method Zajezdy             setId()                   Sets the current record's "id" value
 * @method Zajezdy             setName()                 Sets the current record's "name" value
 * @method Zajezdy             setDestinaceId()          Sets the current record's "destinace_id" value
 * @method Zajezdy             setOblastId()             Sets the current record's "oblast_id" value
 * @method Zajezdy             setKat()                  Sets the current record's "kat" value
 * @method Zajezdy             setTypId()                Sets the current record's "typ_id" value
 * @method Zajezdy             setCenaOd()               Sets the current record's "cena_od" value
 * @method Zajezdy             setCenaTyp()              Sets the current record's "cena_typ" value
 * @method Zajezdy             setCenyId()               Sets the current record's "ceny_id" value
 * @method Zajezdy             setCeny2Id()              Sets the current record's "ceny2_id" value
 * @method Zajezdy             setObrazek()              Sets the current record's "obrazek" value
 * @method Zajezdy             setGalleryId()            Sets the current record's "gallery_id" value
 * @method Zajezdy             setPublikovat()           Sets the current record's "publikovat" value
 * @method Zajezdy             setMaxPocetOsob()         Sets the current record's "max_pocet_osob" value
 * @method Zajezdy             setMaxPristilka()         Sets the current record's "max_pristilka" value
 * @method Zajezdy             setPopisList()            Sets the current record's "popis_list" value
 * @method Zajezdy             setPopisDetail()          Sets the current record's "popis_detail" value
 * @method Zajezdy             setLastMinute()           Sets the current record's "last_minute" value
 * @method Zajezdy             setCenaLastMinute()       Sets the current record's "cena_last_minute" value
 * @method Zajezdy             setLastMinuteDo()         Sets the current record's "last_minute_do" value
 * @method Zajezdy             setCenyLastMinuteId()     Sets the current record's "ceny_last_minute_id" value
 * @method Zajezdy             setCenyLastMinute2Id()    Sets the current record's "ceny_last_minute2_id" value
 * @method Zajezdy             setPopisPodCenikem()      Sets the current record's "popis_pod_cenikem" value
 * @method Zajezdy             setAkce()                 Sets the current record's "akce" value
 * @method Zajezdy             setAutobus()              Sets the current record's "autobus" value
 * @method Zajezdy             setParkoviste()           Sets the current record's "parkoviste" value
 * @method Zajezdy             setKlimatizace()          Sets the current record's "klimatizace" value
 * @method Zajezdy             setBazen()                Sets the current record's "bazen" value
 * @method Zajezdy             setStrava()               Sets the current record's "strava" value
 * @method Zajezdy             setInternet()             Sets the current record's "internet" value
 * @method Zajezdy             setPlazovyServis()        Sets the current record's "plazovy_servis" value
 * @method Zajezdy             setTv()                   Sets the current record's "tv" value
 * @method Zajezdy             setZvire()                Sets the current record's "zvire" value
 * @method Zajezdy             setAdrMapGoogle()         Sets the current record's "adr_map_google" value
 * @method Zajezdy             setPromovatHpDo()         Sets the current record's "promovat_hp_do" value
 * @method Zajezdy             setPromovatHpPos()        Sets the current record's "promovat_hp_pos" value
 * @method Zajezdy             setKeywords()             Sets the current record's "keywords" value
 * @method Zajezdy             setDescription()          Sets the current record's "description" value
 * @method Zajezdy             setDetail()               Sets the current record's "detail" value
 * @method Zajezdy             setZobrazeno()            Sets the current record's "zobrazeno" value
 * @method Zajezdy             setImprese()              Sets the current record's "imprese" value
 * @method Zajezdy             setZacatek()              Sets the current record's "zacatek" value
 * @method Zajezdy             setKonec()                Sets the current record's "konec" value
 * @method Zajezdy             setPoradi()               Sets the current record's "poradi" value
 * @method Zajezdy             setGallery()              Sets the current record's "Gallery" value
 * @method Zajezdy             setTyp()                  Sets the current record's "Typ" value
 * @method Zajezdy             setOblast()               Sets the current record's "Oblast" value
 * @method Zajezdy             setDestinace()            Sets the current record's "Destinace" value
 * @method Zajezdy             setCeny()                 Sets the current record's "Ceny" value
 * @method Zajezdy             setCenyLastMinute()       Sets the current record's "CenyLastMinute" value
 * @method Zajezdy             setCeny2()                Sets the current record's "Ceny2" value
 * @method Zajezdy             setCenyLastMinute2()      Sets the current record's "CenyLastMinute2" value
 * @method Zajezdy             setCenaTyp()              Sets the current record's "CenaTyp" value
 * @method Zajezdy             setHpPromovat()           Sets the current record's "Hp_promovat" collection
 * @method Zajezdy             setAktuality()            Sets the current record's "Aktuality" collection
 * 
 * @package    caitalia
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseZajezdy extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('zajezdy');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('destinace_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('oblast_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('kat', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Leto',
              1 => 'Zima',
              2 => 'Agroturistika',
             ),
             'default' => 'Leto',
             ));
        $this->hasColumn('typ_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('cena_od', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('cena_typ', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ceny_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ceny2_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('obrazek', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('gallery_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('publikovat', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('max_pocet_osob', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('max_pristilka', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('popis_list', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('popis_detail', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('last_minute', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('cena_last_minute', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('last_minute_do', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('ceny_last_minute_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ceny_last_minute2_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('popis_pod_cenikem', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('akce', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('autobus', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('parkoviste', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('klimatizace', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('bazen', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('strava', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('internet', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('plazovy_servis', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('tv', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('zvire', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('adr_map_google', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('promovat_hp_do', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('promovat_hp_pos', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('keywords', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('detail', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
        $this->hasColumn('zobrazeno', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
        $this->hasColumn('imprese', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('zacatek', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('konec', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('poradi', 'integer', null, array(
             'type' => 'integer',
             ));


        $this->index('datum', array(
             'fields' => 
             array(
              'zacatek' => 
              array(
              'sorting' => 'ASC',
              ),
              'konec' => 
              array(
              'sorting' => 'ASC',
              ),
              'imprese' => 
              array(
              'sorting' => 'ASC',
              ),
              'publikovat' => 
              array(
              'sorting' => 'ASC',
              ),
             ),
             ));
        $this->index('sorting', array(
             'fields' => 
             array(
              'zobrazeno' => 
              array(
              'sorting' => 'ASC',
              ),
             ),
             ));
        $this->index('vypis', array(
             'fields' => 
             array(
              'zacatek' => 
              array(
              'sorting' => 'ASC',
              ),
              'id' => 
              array(
              'sorting' => 'ASC',
              ),
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Gallery', array(
             'local' => 'gallery_id',
             'foreign' => 'id'));

        $this->hasOne('Typ', array(
             'local' => 'typ_id',
             'foreign' => 'id'));

        $this->hasOne('Oblast', array(
             'local' => 'oblast_id',
             'foreign' => 'id'));

        $this->hasOne('Destinace', array(
             'local' => 'destinace_id',
             'foreign' => 'id'));

        $this->hasOne('Ceny', array(
             'local' => 'ceny_id',
             'foreign' => 'id'));

        $this->hasOne('Ceny as CenyLastMinute', array(
             'local' => 'ceny_last_minute_id',
             'foreign' => 'id'));

        $this->hasOne('Ceny as Ceny2', array(
             'local' => 'ceny2_id',
             'foreign' => 'id'));

        $this->hasOne('Ceny as CenyLastMinute2', array(
             'local' => 'ceny_last_minute2_id',
             'foreign' => 'id'));

        $this->hasOne('CenaTyp', array(
             'local' => 'cena_typ',
             'foreign' => 'id'));

        $this->hasMany('Hp_promovat', array(
             'local' => 'id',
             'foreign' => 'zajezdy_id'));

        $this->hasMany('Aktuality', array(
             'local' => 'id',
             'foreign' => 'zajezdy_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'name',
             ),
             'canUpdate' => true,
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}