<?php

/**
 * BaseSeo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property clob $popis
 * @property string $keywords
 * @property string $description
 * @property string $title
 * 
 * @method integer getId()          Returns the current record's "id" value
 * @method string  getName()        Returns the current record's "name" value
 * @method clob    getPopis()       Returns the current record's "popis" value
 * @method string  getKeywords()    Returns the current record's "keywords" value
 * @method string  getDescription() Returns the current record's "description" value
 * @method string  getTitle()       Returns the current record's "title" value
 * @method Seo     setId()          Sets the current record's "id" value
 * @method Seo     setName()        Sets the current record's "name" value
 * @method Seo     setPopis()       Sets the current record's "popis" value
 * @method Seo     setKeywords()    Sets the current record's "keywords" value
 * @method Seo     setDescription() Sets the current record's "description" value
 * @method Seo     setTitle()       Sets the current record's "title" value
 * 
 * @package    caitalia
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSeo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('seo');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('popis', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('keywords', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}