<?php

/**
 * BaseZajezdKategorie
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $zajezd_id
 * @property integer $kategorie_id
 * @property Kategorie $Kategorie
 * 
 * @method integer         getZajezdId()     Returns the current record's "zajezd_id" value
 * @method integer         getKategorieId()  Returns the current record's "kategorie_id" value
 * @method Kategorie       getKategorie()    Returns the current record's "Kategorie" value
 * @method ZajezdKategorie setZajezdId()     Sets the current record's "zajezd_id" value
 * @method ZajezdKategorie setKategorieId()  Sets the current record's "kategorie_id" value
 * @method ZajezdKategorie setKategorie()    Sets the current record's "Kategorie" value
 * 
 * @package    caitalia
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseZajezdKategorie extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('zajezd_kategorie');
        $this->hasColumn('zajezd_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('kategorie_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Kategorie', array(
             'local' => 'kategorie_id',
             'foreign' => 'id'));
    }
}