<?php

/**
 * CenaTypTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CenaTypTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CenaTypTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CenaTyp');
    }
}