<?php

/**
 * CenyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CenyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CenyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Ceny');
    }


    function retrieveForSelect($q, $limit = 5) {
        $q = Doctrine_Query::create()
                        ->from('Ceny')
                        ->andWhere('name like ?', '%' . $q . '%')
                        ->addOrderBy('name')
                        ->limit($limit);
        $items = array();
        foreach ($q->execute() as $item) {
            $items[$item->getId()] = (string) $item;
        }
        return $items;
    }
}