<?php

/**
 * CenyRadkyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CenyRadkyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CenyRadkyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CenyRadky');
    }
}