<?php

/**
 * DestinaceKategorieTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DestinaceKategorieTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DestinaceKategorieTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DestinaceKategorie');
    }
}