<?php

/**
 * DestinaceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DestinaceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DestinaceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Destinace');
    }
}