<?php

/**
 * DestinaceRegionyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DestinaceRegionyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DestinaceRegionyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DestinaceRegiony');
    }
}