<?php

/**
 * DolniOdkazyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DolniOdkazyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DolniOdkazyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DolniOdkazy');
    }
}