<?php

/**
 * Hp_imgTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Hp_imgTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Hp_imgTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Hp_img');
    }
}