<?php

/**
 * Hp_promovatTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Hp_promovatTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Hp_promovatTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Hp_promovat');
    }
}