<?php

/**
 * OblastTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OblastTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OblastTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Oblast');
    }
}