<?php

/**
 * ObrazkoveOdkazyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ObrazkoveOdkazyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ObrazkoveOdkazyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ObrazkoveOdkazy');
    }
}