<?php

/**
 * RegionyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RegionyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RegionyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Regiony');
    }
}