<?php

/**
 * ReklamaPoziceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReklamaPoziceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReklamaPoziceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ReklamaPozice');
    }
}