<?php

/**
 * Reklama_poziceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Reklama_poziceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Reklama_poziceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Reklama_pozice');
    }
}