<?php

/**
 * Reklama_statistikaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Reklama_statistikaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Reklama_statistikaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Reklama_statistika');
    }
}