<?php

/**
 * ReklamaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReklamaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReklamaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Reklama');
    }
}