<?php

/**
 * Seo_textTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Seo_textTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Seo_textTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Seo_text');
    }
}