<?php

/**
 * SettingItalia2012Table
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SettingItalia2012Table extends SettingTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object SettingItalia2012Table
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SettingItalia2012');
    }
}