<?php

/**
 * SettingItalia2012
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    caitalia
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class SettingItalia2012 extends BaseSettingItalia2012
{
}
