<?php

/**
 * TypTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TypTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TypTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Typ');
    }
}