<?php

/**
 * ZajezdyKategorieTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ZajezdyKategorieTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ZajezdyKategorieTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ZajezdyKategorie');
    }
}