<?php

/**
 * Zajezdy
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    caitalia
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Zajezdy extends BaseZajezdy
{

    public function save(Doctrine_Connection $conn = null)
    {
        $conn = $conn ? $conn : $this->getTable()->getConnection();
        $conn->beginTransaction();
        try
        {
            $ret = parent::save($conn);

            $this->updateLuceneIndex();

            $conn->commit();

            return $ret;
        }
        catch (Exception $e)
        {
            $conn->rollBack();
            throw $e;
        }
    }

    public function delete(Doctrine_Connection $conn = null)
    {
        $index = ZajezdyTable::getLuceneIndex();

        foreach ($index->find('pk:'.$this->getId()) as $hit)
        {
            $index->delete($hit->id);
        }

        return parent::delete($conn);
    }

    public function updateLuceneIndex()
    {
        $index = ZajezdyTable::getLuceneIndex();

        // remove existing entries
        foreach ($index->find('pk:'.$this->getId()) as $hit)
        {
            $index->delete($hit->id);
        }

        // preskocime nepublikovane zajezdy
        if (!$this->getPublikovat())
        {
            return;
        }

        $doc = new Zend_Search_Lucene_Document();

        // store item primary key to identify it in the search results
        $doc->addField(Zend_Search_Lucene_Field::Keyword('pk', $this->getId()));

        // index job fields
        $doc->addField(Zend_Search_Lucene_Field::UnStored('popis_list', $this->getPopisList(), 'utf-8'));
        $doc->addField(Zend_Search_Lucene_Field::UnStored('popis_detail', $this->getPopisDetail(), 'utf-8'));
        $doc->addField(Zend_Search_Lucene_Field::UnStored('name', $this->getName(), 'utf-8'));

        // add item to the index
        $index->addDocument($doc);
        $index->commit();
    }

    public static function luceneReindex()
    {
        $items = Doctrine_Query::create()
                        ->from('Zajezdy a')
                        ->Where('a.publikovat = 1')
                        ->execute();

        ob_start();

        $index = ZajezdyTable::getLuceneIndex();
        // remove existing entries
        foreach ($items as $item)
        {
            ob_flush();
            flush();
            foreach ($index->find('pk:'.$item->getId()) as $hit)
            {
                $index->delete($hit->id);
            }

            $doc = new Zend_Search_Lucene_Document();

            // store item primary key to identify it in the search results
            $doc->addField(Zend_Search_Lucene_Field::Keyword('pk', $item->getId()));

            // index job fields
        $doc->addField(Zend_Search_Lucene_Field::UnStored('popis_list', $item->getPopisList(), 'utf-8'));
        $doc->addField(Zend_Search_Lucene_Field::UnStored('popis_detail', $item->getPopisDetail(), 'utf-8'));
        $doc->addField(Zend_Search_Lucene_Field::UnStored('name', $item->getName(), 'utf-8'));

            // add item to the index
            $index->addDocument($doc);
            $index->commit();
        }
    }


}
