# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        CA Italia
    description:  Portal CA Italia
    keywords:     dovolená itálie, apartmán, hotel, itálie, rodinná dovolená
    language:     cs
    robots:       index, follow
    author:       Jan Damek

  stylesheets:    [main.css, layout.css, colorbox.css, style_leto.css]

  javascripts:
    - jquery-1.4.4.min.js
    - site.js
    - colorbox/jquery.colorbox.js
    - jquery-ui-1.8.10.custom.min.js
    - scriptaculous-js-1.9.0/lib/prototype.js
    - scriptaculous-js-1.9.0/src/scriptaculous.js?load=effects,builder
    - http://maps.google.com/maps/api/js?sensor=false&amp;region=CS
    - http://connect.facebook.net/cs_CZ/all.js#xfbml=1

  has_layout:     true
  layout:         layout
