regiony:
  class: sfDoctrineRouteCollection
  options:
    model:                Regiony
    module:               regiony
    prefix_path:          /regiony
    column:               id
    with_wildcard_routes: true

obrazkove_odkazy:
  class: sfDoctrineRouteCollection
  options:
    model:                ObrazkoveOdkazy
    module:               obrazkove_odkazy
    prefix_path:          /obrazkove_odkazy
    column:               id
    with_wildcard_routes: true

dolni_odkazy:
  class: sfDoctrineRouteCollection
  options:
    model:                DolniOdkazy
    module:               dolni_odkazy
    prefix_path:          /dolni_odkazy
    column:               id
    with_wildcard_routes: true

setting_italia2012:
  class: sfDoctrineRouteCollection
  options:
    model:                SettingItalia2012
    module:               setting_italia2012
    prefix_path:          /setting_italia2012
    column:               id
    with_wildcard_routes: true

destinace:
  class: sfDoctrineRouteCollection
  options:
    model:                destinace
    module:               destinace
    prefix_path:          /destinace
    column:               id
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing


sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }
  
# default rules
homepage:
  url:   /
  param: { module: destinace, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
