generator:
  class: sfDoctrineGenerator
  param:
    model_class:           reklama
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          reklama
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [=name, zacatek, konec, reklama_pozice, zobrazeno]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
