generator:
  class: sfDoctrineGenerator
  param:
    model_class:           cenyradky
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          cenyradky
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [Ceny, is_active, radek, sl_od, sl_do]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
