<?php echo $form['ceny_radek'][$num]['is_active']->render() ?>
<?php echo $form['ceny_radek'][$num]['radek']->render() ?>
<?php echo $form['ceny_radek'][$num]['sl_od']->render() ?>
<?php echo $form['ceny_radek'][$num]['sl_do']->render() ?>
<?php echo $form['ceny_radek'][$num]['min_noc']->render() ?>
<?php echo $form['ceny_radek'][$num]['sl1']->render() ?>
<?php echo $form['ceny_radek'][$num]['sl2']->render() ?>
<?php echo $form['ceny_radek'][$num]['sl3']->render() ?>
<?php echo $form['ceny_radek'][$num]['sl4']->render() ?>
<?php echo $form['ceny_radek'][$num]['sl5']->render() ?>
<?php echo $form['ceny_radek'][$num]['sl6']->render() ?>
<?php echo $form['ceny_radek'][$num]['sl7']->render() ?>
<?php echo $form['ceny_radek'][$num]['sl8']->render() ?>
<?php echo $form['ceny_radek'][$num]['sl9']->render() ?>
<?php echo $form['ceny_radek'][$num]['bonus1']->render() ?>
<?php echo $form['ceny_radek'][$num]['bonus1_p']->render() ?>
<?php echo $form['ceny_radek'][$num]['bonus2']->render() ?>
<?php echo $form['ceny_radek'][$num]['bonus2_p']->render() ?>
<?php echo $form['ceny_radek'][$num]['bonus3']->render() ?>
<?php echo $form['ceny_radek'][$num]['bonus3_p']->render() ?>
<?php echo $form['ceny_radek'][$num]['bonus4']->render() ?>
<?php echo $form['ceny_radek'][$num]['bonus4_p']->render() ?>
<?php echo $form['ceny_radek'][$num]['bonus5']->render() ?>
<?php echo $form['ceny_radek'][$num]['bonus5_p']->render() ?>
<?php echo $form['ceny_radek'][$num]['bonus6']->render() ?>
<?php echo $form['ceny_radek'][$num]['bonus6_p']->render() ?>
<?php echo $form['ceny_radek'][$num]['bonus7']->render() ?>
<?php echo $form['ceny_radek'][$num]['bonus7_p']->render() ?>
<?php echo $form['ceny_radek'][$num]['bonus8']->render() ?>
<?php echo $form['ceny_radek'][$num]['bonus8_p']->render() ?>
<?php echo $form['ceny_radek'][$num]['bonus9']->render() ?>
<?php echo $form['ceny_radek'][$num]['bonus9_p']->render() ?>
<?php echo $form['ceny_radek'][$num]['sleva1']->render() ?>
<?php echo $form['ceny_radek'][$num]['sleva1_p']->render() ?>
<?php echo $form['ceny_radek'][$num]['sleva2']->render() ?>
<?php echo $form['ceny_radek'][$num]['sleva2_p']->render() ?>
<?php echo $form['ceny_radek'][$num]['sleva3']->render() ?>
<?php echo $form['ceny_radek'][$num]['sleva3_p']->render() ?>
<?php echo $form['ceny_radek'][$num]['sleva4']->render() ?>
<?php echo $form['ceny_radek'][$num]['sleva4_p']->render() ?>
<?php echo $form['ceny_radek'][$num]['sleva5']->render() ?>
<?php echo $form['ceny_radek'][$num]['sleva5_p']->render() ?>
<?php echo $form['ceny_radek'][$num]['sleva6']->render() ?>
<?php echo $form['ceny_radek'][$num]['sleva6_p']->render() ?>
<?php echo $form['ceny_radek'][$num]['sleva7']->render() ?>
<?php echo $form['ceny_radek'][$num]['sleva7_p']->render() ?>
<?php echo $form['ceny_radek'][$num]['sleva8']->render() ?>
<?php echo $form['ceny_radek'][$num]['sleva8_p']->render() ?>
<?php echo $form['ceny_radek'][$num]['sleva9']->render() ?>
<?php echo $form['ceny_radek'][$num]['sleva9_p']->render() ?>