generator:
  class: sfDoctrineGenerator
  param:
    model_class:           hp_img
    theme:                 admin
    non_verbose_templates: true
    with_show:             true
    singular:              ~
    plural:                ~
    route_prefix:          hp_img
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [alt,title,url,zobrazeno]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
